spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lms
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: 8484
